$(function(){
  $(".modalbtn1").click(function(){
    $(".login-modal-wrapper").fadeIn();
  });
   $(".modalbtn2").click(function(){
    $(".login-modal-wrapper").fadeIn();
  });
  $('.close-modal').click(function(){
  $('.login-modal-wrapper').fadeOut();
  });
});
