$(function(){
   $(".modalbtn").click(function(){
    $(".login-modal-wrapper").fadeIn();
  });
  $('.close-modal').click(function(){
  $('.login-modal-wrapper').fadeOut();
  });
  $('h1').text('hello');
});
